### PR TITLE
Draft PyArrow Dataset reader impl

### LINKED ISSUE #10: Support reading from PyArrow datasets
Given the success of the [Datasets  + DuckDB integration](https://duckdb.org/2021/12/03/duck-arrow.html), a similar integration might be worthwhile in this module.

The datasets API allows taking filters and columns subset, and provides an iterator of Arrow record batches. I think that could be wrapped in a [`TableProvider`](https://docs.rs/datafusion/1.0.0/datafusion/datasource/datasource/trait.TableProvider.html#impl-TableProvider), though I'm unclear how predicate pushdown is implemented in Datafusion.

### PR DESCRIPTION
**Pull request by wjones127**
Work in progress. Working toward being able to stream record batches from a PyArrow dataset.

Fixes #10.

### CODE REVIEW

**Comment by wjones127** [comment]
FYI I am going to set this aside for now, since I think this really needs the Arrow C Stream Interface to be reliable. Right now it just wraps a Python iterator and holds onto the GIL while waiting for the PyArrow scanner to generate each batch. I'm running into some GIL deadlocks, so it would be nice to eliminate the GIL stuff from record batch streaming.

**Comment by kylebrooks-8451** [comment]
I believe I have a working solution for this that I developed for the company I work for.  I will get a PR out there soon.  Is there still a need for this?

**Comment by wjones127** [comment]
> I believe I have a working solution for this that I developed for the company I work for. I will get a PR out there soon. Is there still a need for this?

This was mostly an experimental curiosity, but a PR would be cool if you are willing :)

I probably won't get around to finishing this for a while.

**Comment by kylebrooks-8451** [comment]
@wjones127 I've created a PR, #59 

I couldn't add you as a reviewer after I made the PR but I'd love to have your feedback on it.

**Pull request closed without merging**
