### PR TITLE
Ship the Cargo.lock file in the source distribution

### PR DESCRIPTION
**Pull request by cpcloud**
Ported from apache/arrow-datafusion#1508

### CODE REVIEW

**Comment by cpcloud** [comment]
cc @Jimexist

**Review by houqp — APPROVED** [review]

**Comment by cpcloud** [comment]
This is failing because the cache key used in CI invalid. I'll fix that here.

**Comment by Jimexist** [comment]
thanks @cpcloud - do you want to include the lockfile itself into git?

**Comment by cpcloud** [comment]
Yeah, that's the plan. I'll finish it up tomorrow.

**Pull request merged**
