### PR TITLE
Added ParquetReadOptions to register_parquet.

### PR DESCRIPTION
**Pull request by samkaufman**
This PR adds optional keyword args. to `register_parquet` which update `ParquetReadOptions`' defaults.

### CODE REVIEW

**Comment by Jimexist** [comment]
hi @samkaufman thanks for your contribution - do you mind adding a unit test?

**Comment by samkaufman** [comment]
@Jimexist Happy to. How's the one added in 7bab7161aeeb3fe10a428efb0ee069f562ebbf14?

**Comment by Jimexist** [comment]
do you mind fixing the linter err?

**Comment by samkaufman** [comment]
@Jimexist That should do it.

**Pull request merged**
