### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by Jimexist**
artifact is near the bottom of the page https://github.com/datafusion-contrib/datafusion-python/actions/runs/1956469127

can be downloaded and unzipped and then run:

```bash
python3 -m pip install dist/datafusion-0.5.0-cp36-abi3-macosx_10_7_x86_64.whl
```

or similar commands if you are on Windows or Linux

```
❯ python3
Python 3.9.10 (main, Jan 15 2022, 11:48:04)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datafusion
d>>> datafusion.__version__
'0.5.0'
```

### CODE REVIEW

**Comment by matthewmturner** [comment]
Can we make this wheel? Im on M1 Mac `datafusion-0.4.0-cp36-abi3-macosx_11_0_arm64.whl`

**Comment by matthewmturner** [comment]
testing suite passed building locally

**Comment by Jimexist** [comment]
> Can we make this wheel? Im on M1 Mac `datafusion-0.4.0-cp36-abi3-macosx_11_0_arm64.whl`

@matthewmturner I think we need to see https://github.com/actions/virtual-environments/issues/2187 fixed first

**Comment by matthewmturner** [comment]
Yeah saw that 🙁 sry i wasnt clear - i meant more can we still publish that wheel manually to pypi?

**Comment by Jimexist** [comment]
> Yeah saw that 🙁 sry i wasnt clear - i meant more can we still publish that wheel manually to pypi?

manually uploaded via an M1 machine:

```
❯ python -m pip install -U datafusion
Collecting datafusion
  Downloading datafusion-0.5.0-cp36-abi3-macosx_11_0_arm64.whl (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 8.8 MB/s eta 0:00:00
Collecting pyarrow>=1
  Using cached pyarrow-7.0.0-cp310-cp310-macosx_11_0_arm64.whl (14.6 MB)
Collecting numpy>=1.16.6
  Using cached numpy-1.22.3-cp310-cp310-macosx_11_0_arm64.whl (12.8 MB)
Installing collected packages: numpy, pyarrow, datafusion
Successfully installed datafusion-0.5.0 numpy-1.22.3 pyarrow-7.0.0

```

**Pull request merged**
