### PR TITLE
upgrade datafusion and pyo3

### PR DESCRIPTION
**Pull request by Jimexist**
need to wait for next release of datafusion

### CODE REVIEW

**Comment by matthewmturner** [comment]
@Jimexist Can I test this by using the instructions in How To Develop section of readme?

**Comment by matthewmturner** [comment]
I ran tests on this branch and they passed

**Comment by matthewmturner** [comment]
I'm trying to use this branch to run updated benchmarks for `db-benchmark`

when i use `maturin develop` im able to use it locally as expected.

however, when i use `maturin develop --release` I get the following when trying to import datafusion
```
Python 3.8.9 (default, Oct 26 2021, 07:25:53)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datafusion
Killed: 9
```

Any thoughts on what could cause this?  Im looking into it on my side as well but wanted to raise it here in case anyone was familiar with this.

**Comment by matthewmturner** [comment]
When I build the wheels with `maturin build --release` and install the wheel file directly it works.  I guess you can ignore the above.

**Comment by Jimexist** [comment]
i sometimes will run into kill 9 by OS on my Mac - not sure if it's related but it's not persistent

**Pull request merged**
